config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  root "root#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    enum binding: [:hardcover, :paperback]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all

    sleep 10
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/index.html.erb
<div class="w-4/5 mx-auto">
  <h1 class="mx-auto text-2xl w-fit">The Library</h1>
  <%= turbo_frame_tag "books" do %>
  <table>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.category %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookData</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/root/index.html.erb
<div class="w-4/5 mx-auto">
  <h1 class="mx-auto text-2xl w-fit">The Library Main Page</h1>
  <%= turbo_frame_tag "books", src: books_index_path do %>
    <table class="animate-pulse">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Publisher</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
        <% (1..10).each do %>
          <tr>
            <td><div class="bg-slate-200 h-8 rounded w-64"></div></td>
            <td><div class="bg-slate-200 h-8 rounded w-64"></div></td>
            <td><div class="bg-slate-200 h-8 rounded w-64"></div></td>
            <td><div class="bg-slate-200 h-8 rounded w-64"></div></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>